# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  # set up the test database connection since this doesn't happen
  # automatically outside of a rails app
  require 'yaml'
  # require 'active_record'
  require 'mongoid'
  env = 'test'
  # dbconfig    = YAML.load(File.read('db/config.yml'))
  # Mongoid.load!('./spec/config/mongoid.yml', env)
  Mongoid.load!('./config/mongoid.yml', env)
  # ActiveRecord::Base.establish_connection dbconfig[environment]

  # add the factory girl requires
  require 'factory_girl'
  require 'factories'

  # Clean up all collections before each spec runs.
  config.before do
    Mongoid.purge!
    # Mongoid.logger.level = Logger::DEBUG
    # Moped.logger.level = Logger::DEBUG
  end

  # load ENV settings
  heroku_env = "./config/heroku_env.rb"
  load(heroku_env) if File.exists?(heroku_env)
end
